---
title: "Wine Fallstudie"
author: "Emilia Braun"
date: "2023-04-30"
output: html_document
---
# Daten und Pakete laden

```{r}
library(tidyverse)
library(tidymodels)
library(easystats)
library(corrr)
library(fastDummies)
library(reshape2)
wine <- read.csv("https://gist.githubusercontent.com/tijptjik/9408623/raw/b237fa5848349a14a14e5d4107dc7897c21951f5/wine.csv")
```

# Datenjudo

## Korrelationsmatrix

```{r}
wine_cor <-
  wine |>
  select(is.numeric) |> 
  correlate() |> 
  shave()

# heatmap
corr_matrix <- cor(wine)
corr_melted <- melt(corr_matrix)

ggplot(corr_melted, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() +
  scale_fill_gradient2(low="blue", mid="white", high="red", midpoint=0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title="Korrelations-Heatmap für wine")
```

## Umwandlung

```{r}
wine_f <-
  wine |> 
  mutate(wine_fac = factor(Wine))
```

# Data Split

```{r}
wine_split <- initial_split(wine_f, prop = 0.75, strata = wine_fac)
wine_train <- training(wine_split)
wine_test <- testing(wine_split)
```

# Workflow

## Modell

```{r}

knn_model <-
  nearest_neighbor() |>
  set_mode("classification")
```

## Rezept

```{r}
wine_rec <-
  recipe(wine_fac ~ Flavanoids + OD + Proline ,
         data = wine_train) %>%
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors()) %>% 
  step_impute_median(all_predictors()) 
```

## Workflow definieren

```{r}
wine_wflow1 <-
  workflow() %>%
  add_recipe(wine_rec) %>%
  add_model(knn_model)
```

# Tuning

## Model tunen

```{r}
knn_model2 <- nearest_neighbor(mode = "classification", neighbors = tune()) %>%
  set_engine("kknn") %>%
  set_mode("classification")

knn_model2 %>% 
  extract_parameter_dials("neighbors")

wine_wflow2 <-
  wine_wflow1 %>% 
  update_model(knn_model2)
```

# Resampling

## Kreuzvalidierung

```{r}
wine_folds <- vfold_cv(wine_train, strata = "wine_fac")
```

## Tuning Modelle berechnen

```{r}

knn_grid <- grid_regular(neighbors(range = c(1, 20)))

wine_wf3 <- workflow() %>%
  add_recipe(wine_rec) %>%
  add_model(knn_model2) %>%
  tune_grid(knn_grid, resamples = wine_folds)

autoplot(wine_wf3)
```

## Bestes Sample

```{r}
collect_metrics(wine_wf3)
show_best(wine_wf3)
```

# Fitten des train-samples

```{r}

best_wine <-  select_best(wine_wf3)

wine_wfl3_final <- finalize_workflow(wine_wflow2, best_wine)

wine_last_fit <- last_fit(wine_wfl3_final, wine_split)

collect_metrics(wine_last_fit)
```

# Predictions

```{r}
wine_test_predictions <- 
  wine_last_fit %>% 
  collect_predictions() 

confusion <- wine_test_predictions |>
             conf_mat(truth = wine_fac, estimate = .pred_class)
confusion
```


