---
title: "S&P 500 2001-2005"
author: "Nils"
date: "2023-04-19"
output: html_document
---

```{r}
library(tidymodels)
library(tidyverse)
library(easystats)
```

```{r}
sp500 <- read_csv("Smarket.csv")

sp500 <- sp500 %>% 
  rename(ID = ...1)

sum(is.na(sp500))
```

```{r}
set.seed(42)
d_split <- initial_split(sp500)
d_train <- training(d_split)
d_test <- testing(d_split)
```

```{r}
lm <- lm(Today ~ Lag1 + Year, data = d_train)
summary(lm)


recipe_knn <- recipe(Today ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5, data = d_train)
```

```{r}
knn_modell <- nearest_neighbor(
  mode = "regression",
  neighbors = tune()
)

wflow_knn <- workflow() %>% 
  add_recipe(recipe_knn) %>% 
  add_model(knn_modell)
```

```{r}
set.seed(42)
folds <- vfold_cv(d_train, v = 5, repeats = 2)

d_resample <- tune_grid(wflow_knn, resamples = folds, control = control_grid(save_workflow = T),
                        grid = grid_regular(neighbors(range = c(1,10))))


d_resample %>% collect_metrics()
autoplot(d_resample)
```

```{r}
show_best(d_resample, metric = "rmse")
show_best(d_resample, metric = "rsq")

fitbest <- fit_best(d_resample, metric = "rsq") #mein Modell
fitbest
```

```{r}
fit_last <- last_fit(fitbest, d_split)
fit_last %>% collect_metrics() #rmse 1.35; rsq 00.007
```

```{r}
test_mit_vorhersage <- 
  augment(fitbest, new_data = d_test) #gleiches Ergebnis

test_mit_vorhersage <- test_mit_vorhersage %>% 
  mutate(Direction_pred = case_when(
    .pred > 0 ~ "Up",
    .pred < 0 ~ "Down"
  ))

test_mit_vorhersage %>% 
  count(Direction == Direction_pred) %>% 
  mutate(Anteil = n/sum(n))
```












